### ISSUE TITLE
Skse on nexus mods not compatible with patched game

### ISSUE THREAD

**Issue by jmslxblack** [dragonbornsfate/dragonbornsfate.github.io#23]
SKSE step
by patching the game to 1.5.97 (earlier step ) the skse link to nexus mods is wrong ( the patch and skse are incompatible versions) 
using the version corresponding version of skse found at https://skse.silverlock.org/ works.

**Comment by VishVadeva50** [comment]
![image](https://user-images.githubusercontent.com/92656695/226124554-7cab43bb-b52f-4de9-bf5f-e81c816c0a21.png)
